App_Blog/urls.py
from django.urls import path
from . import views

app_name = 'App_Blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>', views.liked, name='liked_post'),
    path('unliked/<pk>/', views.unliked, name='unliked_post'),
    path('my_blogs/', views.MyBlogs.as_view(), name='my_blogs'),
    path('edit_blog/<pk>/', views.UpdateBlog.as_view(), name='edit_blog')
]

App_Login/urls.py
from django.urls import path
from . import views

app_name = 'App_Login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('password/', views.change_password, name='change_password'),
    path('change-profile-image/', views.add_pro_pic, name='add_pro_pic'),
    path('change-profile-pic/', views.change_pro_pic, name='change_pro_pic'),
]

Blog_Project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.index, name='index'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pic')

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import UserProfile
from django.db import models
from django.forms import fields


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True, label="Email Address")

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')


class ProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, logout, authenticate
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm, UserProfileChange, ProfilePic
from django.contrib import messages

def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    
    dict = {'form': form, 'registered': registered}
    return render(request, 'App_Login/signup.html', context=dict)


def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
    
    return render(request, 'App_Login/login.html', context={'form': form})


@login_required
def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('App_Login:login'))


@login_required
def profile(request):
    return render(request, 'App_Login/profile.html', context={})


@login_required
def profile_update(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            return profile(request)
   
    return render(request, 'App_Login/profile_update.html', context={'form': form})


@login_required
def change_password(request):
    current_user = request.user
    
    form = PasswordChangeForm(current_user)
    
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Password Changed Successfully! Please Login With New Password.')
            return HttpResponseRedirect(reverse('index'))
                 
    return render(request, 'App_Login/change_pass.html', context={'form':form})


@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
    
    return render(request, 'App_Login/pro_pic_add.html', context={'form':form})


@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))
                                        
    return render(request, 'App_Login/pro_pic_add.html', context={'form': form})
    
          
    
    

templates/App_Login/change_pass.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block title %} Change Password {% endblock%} 

{% block body_block %}
    <h2>Change Your Password</h2>
    <form method=post>
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit" class="btn btn-primary" btn-sm>Change</button>
    </form>
{% endblock%}

templates/App_Login/login.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block title %} Login {% endblock%} 

{% block body_block %}

    <h2>Login Your Account</h2>
    <form method=post>
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit" class="btn btn-primary" btn-sm>Login</button>
    </form>
{% endblock%}

templates/App_Login/pro_pic_add.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block title %} Profile Pic {% endblock%} 

{% block body_block %}

    <h2>Add Your Profile Picture</h2>
    <form method=post enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit" class="btn btn-primary" btn-sm>Add Profile Picture</button>
    </form>
{% endblock%}

templates/App_Login/profile.html
{% extends 'layout.html' %}

{% block title %} Profile {% endblock%} 

{% block body_block %}
    <h2>Your Profile</h2>

    {% if user.user_profile %}
        <img src="/media/{{user.user_profile.profile_pic}}" alt="" class="rounded-circle" width="120px">
        <br><br>
        <a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Pic</a>
    {% else %}
        <img src="/media/profile_pic_default.jpg" alt="" class="rounded-circle" width="120px">
        <br>
        <a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Pic</a>
    {% endif %}

    <br><br>

    <p>Username: {{ user.username }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Name: {{ user.first_name }} {{ user.last_name }}</p>

    <br>
    <a href="{% url 'App_Login:profile_update' %}" class="btn btn-warning btn-sm">Update Profile</a>
{% endblock%}

templates/App_Login/profile_update.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block title %} Update Profile {% endblock%} 

{% block body_block %}
    <h2>Update Your Profile</h2>
    <form method=post>
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit" class="btn btn-primary" btn-sm>Update</button>
    </form>
{% endblock%}

templates/App_Login/signup.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% block title %} Sign Up {% endblock%} 

{% block body_block %}
    {% if registered %}
        <div class="alert alert-primary" role="alert">
            Account Created Successfully <a href="{% url 'App_Login:login' %}">Login Here</a>
        </div>
    {% else %}
    <h2>Create New Account</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" btn-sm>Create Account</button>
    </form>
    <br>
    <p>Already Have Account? <a href="{% url 'App_Login:login' %}">Login Here</a></p>
    {% endif %}
{% endblock%}